name: Android CI

on: [push, workflow_dispatch]

jobs:
    build:

        runs-on: ubuntu-latest
        outputs:
            setting-file: ${{ steps.publish.outputs.setting-file }}
        steps:
        - uses: actions/checkout@v4
        - name: set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: gradle

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Build with Gradle
          run: ./gradlew build
        - name: Publish Kotlin filename
          id: publish
          run: find *.kts -type f -execdir echo 'setting-file={}' >> $GITHUB_OUTPUT ';'
        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: settings
            path: settings.gradle.kts
    deploy:
        needs: build 
        runs-on: ubuntu-latest   
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v4
              with:
                name: settings
            - name: Output contents
              run: ls
            - name: Output filename
              run: echo "${{ needs.build.outputs.setting-file }}"
            - name: Deploy
              run: echo "Deploying..."