name: First Workflow
on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Which agent are you?
        options:
        - orange
        - apple
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello ${{ inputs.name }}!"
      - name: Print goodbye
        run: echo "Done - bye!"
