name: First Workflow
on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Which agent are you?
        default: 'apple'
        options:
        - orange
        - apple
  schedule:
    - cron: '30 5,17 * * *'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello ${{ inputs.name }}!"
      - name: Print goodbye
        run: echo "Done - bye!"
