name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the deployable artifact files
                required: false
                default: test-report
                type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v4
              with:
               name: ${{ inputs.artifact-name }}
            - name:
              run: ls   
            - name: Output Information
              run: echo "Deploying & uploading..."